config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/:page" => "pages#index", as: :pages
  post "pages/form_submit" => "pages#form_submit", as: :form_submit

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        page = params[:page] || :home
        render page
    end

    def form_submit
        redirect_to :root
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <!-- Bootstrap -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          <img alt="Brand" src="/assets/index.png">
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", pages_path(page: :home) %></li>
          <li><%= link_to "Team", pages_path(page: :team) %></li>
          <li><%= link_to "Services", pages_path(page: :service) %></li>
          <li><%= link_to "Patient-infos", pages_path(page: :patient) %></li>
          <li><%= link_to "Documents", pages_path(page: :document) %></li>
          <li><%= link_to "Contact", pages_path(page: :contact) %></li>
          <li><%= link_to "Impressum", pages_path(page: :impressum) %></li>
          <li><%= link_to "Contact - Clients", pages_path(page: :cclient) %></li>
          <li><%= link_to "Contact - Doctors", pages_path(page: :cdoctor) %></li>
          <li><%= link_to "Pictures", pages_path(page: :picture) %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <div class="jumbotron">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/pages/cclient.html.erb
<h1>You can contact us directly via this form, please insert the necessary information</h1>

<div class="row clearfix">
    <div class="col-md-12 column">
        <form class="form-horizontal" role="form" method="post" action="<%= url_for form_submit_path %>">
            <div class="form-group">
                <label for="firstname" class="col-sm-2 control-label">First Name</label>
                <div class="col-sm-10">
                    <input class="form-control" id="firstname" type="text" />
                </div>
            </div>
            <div class="form-group">
                 <label for="lastname" class="col-sm-2 control-label">Last Name</label>
                <div class="col-sm-10">
                    <input class="form-control" id="lastname" type="text" />
                </div>
            </div>
            <div class="form-group">
                 <label for="phonenumber" class="col-sm-2 control-label">Phone Number</label>
                <div class="col-sm-10">
                    <input class="form-control" id="phonenumber" type="text" />
                </div>
            </div>
            <div class="form-group">
                 <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input class="form-control" id="email" type="email" />
                </div>
            </div>
            <div class="form-group">
                 <label for="concern" class="col-sm-2 control-label">Your Concern</label>
                <div class="col-sm-10">
                    <textarea class="form-control" id="concern"> </textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-default">Send</button>
                </div>
            </div>
            <%= hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %>
        </form>
    </div>
</div>

app/views/pages/cdoctor.html.erb
<h1>According to the other document in your folder. if you have questions, contact me.</h1>

app/views/pages/contact.html.erb
<p>Sie finden uns unter folgender Adresse</p>
<p>Praxis Sommer
<br>Rötelstrasse 127
<br>8037 Zürich
<br>Tel: +41 78 842 89 99
<br>Mail: patrice.go@gmx.ch</p>

<div id='map'></div>

<h1>Anfahrt mit dem Auto:</h1>
<p>Die nächsten Parkhäuser sind am Milchbuck und am Bucheggplatz, von dort finden sie die Praxis Sommer innerhalb von 5 min Fussweg. Wir bieten eine Begrenzte anzahl Parkplätze an, für welche wir aber nicht garantieren können, dass diese Frei sind.</p>

<h1>Anfahrt mit den ÖV:</h1>
<p>Von zürich Hauptbahnhof mit dem Tram Nummer 11(Grüne Tram Linie in Richtung ) bis Haltestelle Bucheggplatz, von dort aus ca. 4 min zu Fuss.</p>

<script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDVW2jyL844QNA17tRNWN2tcUiGI7i47Co&sensor=false&extension=.js'></script>

<script>
    google.maps.event.addDomListener(window, 'load', init);
    var map;
    function init() {
        var mapOptions = {
            center: new google.maps.LatLng(47.397244,8.532114),
            zoom: 18,
            zoomControl: true,
            zoomControlOptions: {
                style: google.maps.ZoomControlStyle.DEFAULT,
            },
            disableDoubleClickZoom: true,
            mapTypeControl: true,
            mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
            },
            scaleControl: true,
            scrollwheel: true,
            panControl: true,
            streetViewControl: true,
            draggable : true,
            overviewMapControl: true,
            overviewMapControlOptions: {
                opened: false,
            },
            mapTypeId: google.maps.MapTypeId.ROADMAP,
        }
        var mapElement = document.getElementById('map');
        var map = new google.maps.Map(mapElement, mapOptions);
        var locations = [
['Praxis Sommer', 'undefined', '+41 78 842 89 99v', 'patrice.go@gmx.ch', 'http://www.swispon.com', 47.3972147, 8.532199600000013, 'https://mapbuildr.com/assets/img/markers/default.png']
        ];
        for (i = 0; i < locations.length; i++) {
            if (locations[i][1] =='undefined'){ description ='';} else { description = locations[i][1];}
            if (locations[i][2] =='undefined'){ telephone ='';} else { telephone = locations[i][2];}
            if (locations[i][3] =='undefined'){ email ='';} else { email = locations[i][3];}
           if (locations[i][4] =='undefined'){ web ='';} else { web = locations[i][4];}
           if (locations[i][7] =='undefined'){ markericon ='';} else { markericon = locations[i][7];}
            marker = new google.maps.Marker({
                icon: markericon,
                position: new google.maps.LatLng(locations[i][5], locations[i][6]),
                map: map,
                title: locations[i][0],
                desc: description,
                tel: telephone,
                email: email,
                web: web
            });
if (web.substring(0, 7) != "http://") {
link = "http://" + web;
} else {
link = web;
}
            bindInfoWindow(marker, map, locations[i][0], description, telephone, email, web, link);
     }
 function bindInfoWindow(marker, map, title, desc, telephone, email, web, link) {
      var infoWindowVisible = (function () {
              var currentlyVisible = false;
              return function (visible) {
                  if (visible !== undefined) {
                      currentlyVisible = visible;
                  }
                  return currentlyVisible;
               };
           }());
           iw = new google.maps.InfoWindow();
           google.maps.event.addListener(marker, 'click', function() {
               if (infoWindowVisible()) {
                   iw.close();
                   infoWindowVisible(false);
               } else {
                   var html= "<div style='color:#000;background-color:#fff;padding:5px;width:150px;'><h4>"+title+"</h4><p>"+telephone+"<p><a href='mailto:"+email+"' >"+email+"<a><a href='"+link+"'' >"+web+"<a></div>";
                   iw = new google.maps.InfoWindow({content:html});
                   iw.open(map,marker);
                   infoWindowVisible(true);
               }
        });
        google.maps.event.addListener(iw, 'closeclick', function () {
            infoWindowVisible(false);
        });
 }
}
</script>
<style>
    #map {
        height:400px;
        width:550px;
    }
    .gm-style-iw * {
        display: block;
        width: 100%;
    }
    .gm-style-iw h4, .gm-style-iw p {
        margin: 0;
        padding: 0;
    }
    .gm-style-iw a {
        color: #4272db;
    }
</style>

app/views/pages/document.html.erb
<h1>Downloaden Sie dokumente via Klick auf Den Titel</h1>

<a href="http://www.fbmclearningcenter.com/static/media/uploads/placeholder.pdf">Report1.pdf</a>
<br>
<a href="https://www.ieee.org/documents/ieeecopyrightform.doc">Report2.doc</a>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p>Herzlich Willkommen auf der Seite von Dr. med. Sommer</p>

<h1>Phylosophie</h1>
<p>Ich freue mich, Sie auf meiner Webseite begrüssen zu dürfen.

Die Praxis Sonne wurde von mir bereits im Jahre 1998 gegründet, um mein Fachwissen möglichst vielen Patienten zugänglich zu machen. Zusammen mit meinem freundlichen Team stehe ich Ihnen gerne als kompetenter Ansprechspartner zur Verfügung

Die Konsultationen führe ich in deutscher, französischer, italienischer oder englischer Sprache durch.

Ich verfüge zudem über zwei Operationstage in meiner Praxis oder als Belegarzt in der Klinik im Park (Zürich) und dem See-Spital (Kilchberg und Horgen).</p>

<h1>Specialisations</h1>
<p>Unsere Spezialisation sind:
    <li>Hautkrankheiten</li>
    <li>Geschlechtskrankheiten</li>
    <li>Haarkrankheiten</li>
</p>

<h1>Konsultationszeiten</h1>
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Montag</td>
      <td>8:00 -11:30 und 13:30- 16:00 Uhr</td>
    </tr>
    <tr>
      <td>Dienstag</td>
      <td>8:00 -11:30 und 13:30- 16:00 Uhr</td>
    </tr>
    <tr>
      <td>Mittwoch</td>
      <td>8:00 -11:30 und 13:30- 16:00 Uhr</td>
    </tr>
    <tr>
      <td>Donnerstag</td>
      <td>8:00 -11:30 und 13:30- 16:00 Uhr</td>
    </tr>
    <tr>
      <td>Freitag</td>
      <td>8:00 -11:30 und 13:30- 16:00 Uhr</td>
    </tr>
    <tr>
      <td>Samstag</td>
      <td>Praxis geschlossen</td>
    </tr>
    <tr>
      <td>Sonntag</td>
      <td>Praxis geschlossen</td>
    </tr>
  </tbody>
</table>

<h1>Telephonzeiten</h1>
<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Montag</td>
      <td>8:00 -11:30 Uhr</td>
    </tr>
    <tr>
      <td>Dienstag</td>
      <td>8:00 -11:30 Uhr</td>
    </tr>
    <tr>
      <td>Mittwoch</td>
      <td>8:00 -11:30 Uhr</td>
    </tr>
    <tr>
      <td>Donnerstag</td>
      <td>8:00 -11:30 Uhr</td>
    </tr>
    <tr>
      <td>Freitag</td>
      <td>8:00 -11:30 Uhr</td>
    </tr>
    <tr>
      <td>Samstag</td>
      <td>Praxis geschlossen</td>
    </tr>
    <tr>
      <td>Sonntag</td>
      <td>Praxis geschlossen</td>
    </tr>
  </tbody>
</table>

<h1>Weitere Informationen zur Praxis, dem Leistungsangebot und dem Team finden Sie auf den folgenden Seiten.</h1>

app/views/pages/impressum.html.erb
<h1>Impressum</h1>
<p>
Alle Inhalte dieser Seite werden von Dr. med. Sommer bereitgestellt und erheben keinen Anspruch auf Vollständigkeit oder Korrektheit. Deshalb übernimmt Dr. med. Sommer keine Haftung für dadurch entstandene Schäden und Rechtsansprüche können daraus nicht abgeleitet werden. Der Inhalt von verlinkten Drittseiten untersteht nicht Dr. med. Sommers Zuständigkeit
Diese Website entspricht den Anforderungen des HON (Health on den Net).
Alle Informationen auf dieser Website dienen dazu Auffindbarkeit von Dr. med. Sommer zu vereinfachen und ersetzen keinesfalls eine Konsultation im falle einer Beschwerde. Des weiteren soll Sie Hilfebedürftigen Helfen einen Arzt in ihrer Umgebung zu finden
</p>
<p>
Werbefreiheit / Unabhängigkeit
Die Webseite von Dr. med. Sommer wird von keiner kommerziellen Organisation unterstützt und promoviert auch keine Produkte von bestimmten Firmen.
</p>
<p>
Datenschutz
<br>E-Mails über diese Homepage sind nicht verschlüsselt und die Angaben könnten unter besonderen Umständen durch aussenstehende Personen eingesehen werden.
Besucherinformationen welche über ein Kontaktformular zu uns gelangen, werden  selbstverständlich streng vertraulich behandelt.
Jegliche Daten welche bei einer Anfrage über die Website enstehen, werden direkt nach deren Übermittlung vernichtet, so dass nichts gespeichert oder weiterverwendet werden kann.
Anfragen über die Website werden nach Bearbeitung der Anfrage vernichtet, so dass keine Daten.
</p>
<p>
Copyright
<br>Alle auf dieser Seite verwendeten Texte und Fotos sind Eigentum von Dr. med Sommer. Dessen Verwendung ohne schriftliche zusage von Dr. med. Sommer ist eine strafbare Handlung.
</p>

app/views/pages/patient.html.erb
<h1>Links</h1>
<p>
<br>Notfallwalkin Zürich
<br><a href="http://www.notfallwalkin.ch">www.notfallwalkin.ch</a>
<br>Reiseberatung via Internet
<br><a href="http://www.safetravel.ch">www.safetravel.ch</a>
<br>Kontaktstelle bei Alkoholproblemen (Fachstelle für Alkohol- und andere Drogenprobleme)
<br><a href="http://www.sfa-ispa.ch">www.sfa-ispa.ch</a>
<br>Arbeitsgemeinschaft Tabakprävention
<br><a href="http://www.at-schweiz.ch">www.at-schweiz.ch</a>
<br>Bundesamt für Gesundheit
<br><a href="http://www.admin.ch/bag">www.admin.ch/bag</a>
<br>Krebsfragen
<br><a href="http://www.krebsliga.ch">www.krebsliga.ch</a>
<br>Lungenkrankheiten
<br><a href="http://www.lungenliga.ch">www.lungenliga.ch</a>
<br>Wenn die Kinder krank sind; Ratschläge für Eltern
<br><a href="http://www.swiss-paediatrics.org/parents">www.swiss-paediatrics.org/parents</a>
<br>Arztlexikon
<br><a href="http://www.medizin.ch">www.medizin.ch</a>
<br>Aktiv werden.........fit bleiben!
<br><a href="http://www.active-online.ch">www.active-online.ch</a>
<br>Burnout
<br><a href="http://www.swissburnout.ch">www.swissburnout.ch</a>
<br>Online Beratung zur Sexualität und Liebe für Jugendliche
<br><a href="http://www.durchblick.ch">www.durchblick.ch</a>
<br>Impffragen und Informationen
<br><a href="http://www.infovac.ch">www.infovac.ch</a>
<br>Oswald Oelz: Mediziner, Alpinist und Fotograf der Bilder in unserer Praxis
<br><a href="http://www.oswald-oelz.ch">www.oswald-oelz.ch</a>
</p>

app/views/pages/picture.html.erb
<h1>Have a look at our practice</h1>

<img src="http://placehold.it/350x150"/>
<img src="http://placehold.it/350x150"/>
<img src="http://placehold.it/350x150"/>
<img src="http://placehold.it/350x150"/>
<img src="http://placehold.it/350x150"/>
<img src="http://placehold.it/350x150"/>

app/views/pages/service.html.erb
<p>In der Praxis Sonne bieten wir folgende Dienstleistungen an:</p>

<h1>Innere Medizin</h1>
<li>Second Opinion
<li>Notfallkonsultationen
<li>Check-Up
<li>Impfungen
<li>EKG, Fahrradbelastungen
<li>Digitales Röntgen


<h1>Gastroenterologie</h1>
<li>Reisemedizin
<li>Videoendoskopie des oberen und unteren Verdauungstraktes (Speiseröhre, Magen, Dünn- und Dickdarm)
<ul>
<li>Ergebnis des aktuellen Hygienetests:
<li>www.sggssg.ch (Whitelist Hygienetest anklicken)
</ul>
<li>Helicobacter-Atemtest
<li>Proktologie (Hämorrhoidenbehandlung)
<li>Atemtests auf Laktose-, Fruktoseintoleranz, bakt. Fehlbesiedlung


<h1>Routine- und Spezial-Ultraschall</h1>
<li>Abdomen
<li>Gefässe (Carotis, Nierenarterien)
<li>Schilddrüse
<li>Bewegungsapparat
<li>Kontrastmittelsonographie

app/views/pages/team.html.erb
<img src="http://www.aerztezentrum-sihlcity.ch/img/azs-portrait/dr_abraham_licht.jpg" data-toggle="modal" data-target="#myModal"/>
<h1>KD Dr. med. Sommer</h1>
<p>Spezialisation: FMH Innere Medizin
<br>FMH Intensivmedizin
<br>Facharzt Klinische Notfallmedizin SGNOR
<br>Klinischer Dozent der Universität Zürich</p>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">KD Dr. med. Sommer</h4>
      </div>
      <div class="modal-body">
        <img src="http://www.aerztezentrum-sihlcity.ch/img/azs-portrait/dr_abraham_licht.jpg"/>
        <h1>KD Dr. med. Sommer</h1>
        <p>Spezialisation: FMH Innere Medizin
        <br>FMH Intensivmedizin
        <br>Facharzt Klinische Notfallmedizin SGNOR
        <br>Klinischer Dozent der Universität Zürich</p>
        <p>Dr. med. Sommer hat im Jahr 2003 die Praxis Sonne gegründet, um sein Fachwissen so vielen Patiente“n wie möglich zugänglich zu machen. Seither führt er diese erfolgreich mit Hilfe von Frau Sommer und seiner MPA, Florence Nightingale</p>

        <table class="table">
          <tbody>
            <tr>
              <td>1992</td>
              <td>Staatsexamen</td>
            </tr>
            <tr>
              <td>1993-1995</td>
              <td>Radio-Onkologie, Universitätsspital Zürich, Prof. U. Lütolf</td>
            </tr>
            <tr>
              <td>1995-1997</td>
              <td>Innere Medizin, Universitätsspital Zürich, Prof. A. Schaffner</td>
            </tr>
            <tr>
              <td>1997-1998</td>
              <td>Infektiologie, Universitätsspital Zürich, Prof. R. Weber</td>
            </tr>
            <tr>
              <td>1998-1999</td>
              <td>Hämatologie, Universitätsspital Zürich, Prof. J. Fehr</td>
            </tr>
            <tr>
              <td>1999-2000</td>
              <td>Medizinische Intensivstation, Universitätsspital Zürich., PD Dr. M. Maggiorini</td>
            </tr>
            <tr>
              <td>2000-2001</td>
              <td>Oberarzt, Medizinische Klinik, Stadtspital Triemli Zürich, Prof. O. Oelz</td>
            </tr>
            <tr>
              <td>2001-2003</td>
              <td>Clinical Fellow Critical Care Department, University of Toronto, Canada
<br>Klinische Epidemiologie und Statistik an der University of Toronto</td>
            </tr>
            <tr>
              <td>2003-2004</td>
              <td>Leitender Arzt, Medizinische Klinik, Stadtspital Triemli Zürich, Prof. O. Oelz</td>
            </tr>
            <tr>
              <td>2003-2007</td>
              <td>Teilzeit: Oberarzt, Klinik und Poliklinik für Innere Medizin, Universitätsspital Zürich</td>
            </tr>
            <tr>
              <td>2009-2013</td>
              <td>Teacher of the year, Innere Medizin Universitätsspital Zürich</td>
            </tr>
            <tr>
              <td>seit 2013</td>
              <td>Chefarzt Notfallzentrum Hirslanden</td>
            </tr>
          </tbody>
        </table>
        <p>Akkreditierungen für stationäre Betreuung: Klinik im Park, Spital Sanitas
Fremdsprachen: Englisch, Französisch, Italienisch, Hebräisch</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>